### PR TITLE
Hide slide for app store if disabled

### LINKED ISSUE #285: Regression: Hide appstore splash screen when appstoreenabled=false
Previously implemented in https://github.com/nextcloud/server/issues/13061

The splash screen for the app store is back in 17.0.3 even if disabled, and perhaps earlier.

### Steps to reproduce

1. New Nextcloud install
2. Set `  'appstoreenabled' => false,` in the `config.php` file, and verify with `php occ config:system:get appstoreenabled` showing false
3. Log in, through the web, as a new user.
4. Splash screen 2 (I think) talks about the app store, but it should not.

### PR DESCRIPTION
**Pull request by kesselb**
Fix #285

### CODE REVIEW

File: lib/Controller/WizardController.php [hunk 1]
```diff
@@ -74,19 +74,21 @@ public function disable() {
 	 * @return JsonResponse
 	 */
 	public function show() {
+		$appStore =$this->config->getSystemValue('appstoreenabled', true);
```
Comment (juliushaertl) [inline lib/Controller/WizardController.php]:
```suggestion
		$appStore = $this->config->getSystemValue('appstoreenabled', true);
```

Comment (kesselb) [reply lib/Controller/WizardController.php]: Fixed :see_no_evil:
